### ISSUE TITLE
How to display the file where errors were found ?

### ISSUE THREAD

**Issue by NicolasMassart** [cytopia/linkcheck#21]
Hi,
I ran linkcheck on my markdown folder and it found some errors but is there a way (except searching for the link in all the files) to display the file path where the error was spotted in the linkcheck result directly ?
Thanks.

**Comment by cytopia** [comment]
@NicolasMassart can you check the PR branch and see if that solves your issue without introducing new issues: https://github.com/cytopia/linkcheck/pull/22

Use `-v` to show affected files
